# Project Details
sonar.projectKey=LPMS
sonar.projectName=LPMS Learning Portal
sonar.projectVersion=1.0

# Source Directories to Scan
sonar.sources=server,client/src

# Exclude compiled files and dependencies
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

# Source Encoding
sonar.sourceEncoding=UTF-8
